### ISSUE TITLE
Update plugin to test up to newest WP version

### ISSUE THREAD

**Issue by slavingia** [gumroad/wp-gumroad#10]
https://wordpress.org/plugins/gumroad/#developers

- [x] Test the plugin with the latest version of Wordpress i.e. 4.9.8.
- [x] Update the README.txt to say that the plugin is tested up to 4.9.8.
- [x] Fix incompatibilities if any with the plugin code.
- [x] Update promo images.
- [x] Release a new version.

**Comment by slavingia** [comment]
```
WordPress 5.0 is scheduled to be released on November 19. Are your plugins ready?

After testing your plugins and ensuring compatibility, it only takes a few moments to change the readme "Tested up to:" value to 5.0. This information provides peace of mind to users and helps encourage them to update to the latest version.

Here are the current "Tested up to:" values for each of your plugins:

 * https://wordpress.org/plugins/gumroad/ (tested up to 4.2.21)

For each plugin that is compatible, you don't need to release a new version — just change the stable version's readme value.
```

**Comment by slavingia** [comment]
would be good to do sometime before nov 19 :)

**Comment by sharang-d** [comment]
@slavingia _a 

Did you get that in an email? Have you done any preliminary work on this task or have you not looked into it at all? I don't have any experience with Wordpress(self-hosted and cloud both) so IDK the correct approach to take.
If I understand this correctly these are the tasks we need to perform: 
1. Test the plugin with the latest version of Wordpress i.e. 4.9.8.
2. Fix incompatibilities if any with the plugin code and release a new version.
3. Updated the README.txt to say that the plugin is tested up to 4.9.8.

I created an account on wordpress.com and tried to create a new site but I could not find any "free plan" which some blogs talk about which is why I could not proceed to test the plugin on any Wordpress version at all. I later found a site which provided free wordpress sandboxes to use but I could not set up the HTTPS plugin there and I ended up breaking that sandbox.

I think I'd have to set up a local wordpress.org installation and test this. Please let me know if I'm on the right track so I don't do any unnecessary work.

cc @ershad as I think he has some experience with Wordpress.

**Comment by slavingia** [comment]
I have not looked into it. I think you're exactly right on the steps needed to take. (1,2, and 3).

We can use a Gumroad account to test with – there are login details in 1P for WP.org. Will create a WP.com account now.

**Comment by slavingia** [comment]
Added WP.com account to 1P.

**Comment by slavingia** [comment]
@sharang-d _a it's free but let me know if you want me to upgrade to a paid plan.

**Comment by slavingia** [comment]
A comment from 4 months ago:

> It seems to work just fine with my current version of WP 4.9.6 but I am curious about whether there could be security holes that hackers might exploit with the plugin’s implementation on newer versions of WP.

**Comment by slavingia** [comment]
i'll take care of this, since i prob have the most experience.

**Comment by slavingia** [comment]
done!
